# Generated by Django 4.1.7 on 2023-02-19 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=600, verbose_name='Message')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name')),
                ('sender', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sender')),
                ('number', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone Number')),
                ('transactionId', models.CharField(blank=True, max_length=200, null=True, verbose_name='Transaction Id')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Amount')),
                ('reason', models.CharField(max_length=300, verbose_name='Reason')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Invalid Payments',
                'db_table': 'invalid_payments',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=600, verbose_name='Message')),
                ('name', models.CharField(blank=True, default='default', max_length=300, null=True, verbose_name='Name')),
                ('sender', models.CharField(max_length=250, verbose_name='Sender')),
                ('number', models.CharField(default='default', max_length=13, null=True, verbose_name='Phone Number')),
                ('transactionId', models.CharField(max_length=200, unique=True, verbose_name='Transaction Id')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('is_valid', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payments',
                'db_table': 'payments',
            },
        ),
    ]
